apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: titan-ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing        # Load Balancer will be public
    alb.ingress.kubernetes.io/target-type: ip                 # Route traffic directly to pod IPs
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'   # Only listen on HTTP (80)
    alb.ingress.kubernetes.io/healthcheck-path: /             # Path for health checks
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:917374863672:certificate/f168db2f-3132-4971-825e-41b76a4e7be1  # SSL certificate for HTTPS (can be added later)
spec:
  ingressClassName: alb                                           # Use AWS ALB Ingress Controller
  rules:
    - host: titan.gopinaidu2451.online                           # Uncomment and replace with your domain name when you have it
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: titan-service
                port:
                  number: 80

